matrix:
  include:
    - language: ruby
      rvm:
      - 2.3.3

      before_script:
        - chmod +x ./script/cibuild
      
      script:
      - ./script/cibuild
      
      env:
        global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

      sudo: false 
      exclude: [vendor]

    - language: python
      python: 3.4.2
      before_script:
        - pip3 install colorama
      script:
        - python3 ./script/check_frontmatter.py feature_key tags