matrix:
  include:
    - language: ruby
      rvm:
      - 2.3.3

      before_script:
        - chmod +x ./script/cibuild

      script: ./script/cibuild

      env:
        global:
        - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

      sudo: false
      exclude: [vendor]

    - language: python
      python: 3.4.2
      install: pip3 install -r ./script/pyscripts/requirements.txt
      script:
        - python3 ./script/pyscripts/check_frontmatter.py feature_key tags
        - python3 ./script/pyscripts/post_linter.py --center-images --center-eqs --ignore iframe sup
