language: ruby
rvm:
- 2.3.3

before_script:
  - chmod +x ./script/cibuild
  - pip3 install colorama

script:
 - ./script/cibuild
 - python3 ./script/check_frontmatter.py feature_key tags

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true 

sudo: false 
exclude: [vendor]