title: Kevin Fronczak
description: Analog Circuit Designer
email: kfronczak@gmail.com
domain: 'kevinfronczak.com'
url: "https://kevinfronczak.com"
twitter_username:
github_username: fronzbot
linkedin_username: kfronczak
google_scholar_username: NmzmakYAAAAJ&hl=en
youtube_username: kevinfronczak
google_plus_username: 112051215299289480804
twitter_username: fronzbot
paginate: 5
excerpt_separator: "<!-- more -->"
image_path: /images
doc_path: /assets/docs
code_path: /assets/code

gems:
  - jekyll-paginate
  - kramdown
  - jekyll-assets
  - jekyll-sitemap

# Build settings
markdown: kramdown
highlighter: rouge
encoding: UTF-8
permalink: /blog/:title
include:
  - "_pages"
exclude:
  - ".asset-cache"
  - vendor

google_analytics_id: UA-28009801-1

# Sharing options
social:
  icons: /assets/icons
  twitter: true
  twitter_username: fronzbot
  facebook: true
  gplus: true
  linkedin: true
  reddit: true

# kramdown options
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

# Sass options
sass:
  style: compressed


# Asset compression
compress_html:
  clippings: all
  comments: ["<!--", "-->"]
  endings: all

assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "*.PNG"
    - "*.jpg"
    - "*.bmp"
    - "style.css"
    - "*.pdf"
  sources:
    - assets/css
    - images
    - images/features
    - assets/docs
    - assets/scripts
    - assets/fonts
  features:
    liquid: false
    integrity: false
    # This will add height and width attributes for an img tag.
    automatic_img_size: true
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt : true
