title: Kevin Fronczak
description: Analog Circuit Designer
email: kfronczak@gmail.com
baseurl: "https://fronzbot.github.io"
#url: "https://fronzbot.github.io"
twitter_username:
github_username: fronzbot
linkedin_username: kfronczak
google_scholar_username: NmzmakYAAAAJ&hl=en
youtube_username: kevinfronczak
google_plus_username: 112051215299289480804
paginate: 5
excerpt_separator: "<!-- more -->"
image_path: /assets/images
doc_path: /assets/docs
code_path: /assets/code

gems:
  - jekyll-paginate
  - kramdown
  - jekyll-assets

# Build settings
markdown: kramdown
highlighter: rouge
encoding: UTF-8
permalink: /blog/:title
include:
  - "_pages"
exclude:
  - ".asset-cache"
  - vendor

# Sharing options
social:
  icons: /assets/icons
  twitter: true
  twitter_username: fronzbot
  facebook: true
  gplus: true
  linkedin: true
  reddit: true

# kramdown options
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Asset compression
assets:
  compress:
    css: true
    js: true
  autowrite: true
  cache: .asset-cache
  cache_type: filesystem
  prefix: "/assets"
  digest: true
  assets:
    - "*.png"
    - "bundle.css"
  sources:
    - assets/css
    - assets/images
    - assets/images/features
  features:
    liquid: false
    integrity: false
    # This will add height and width attributes for an img tag.
    automatic_img_size: true
    # This will add the digest path as an alt attribute for an img tag.
    automatic_img_alt : true
